remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
name: Firely Helm Charts
title: Firely Helm repository
description: Firely Helm Repository
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]