apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firely-auth.fullname" . }}-conf
  labels:
    {{- include "firely-auth.labels" . | nindent 4 }}
data:
  FIRELY_AUTH_License__LicenseFile : {{ .Values.license.mountPath }}/{{ .Values.license.fileName }}