{{- if .Values.license.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firely-auth.fullname" . }}-license-secret
  labels:
    {{- include "firely-auth.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.license.fileName }}: {{ .Values.license.value | b64enc }}
{{- end -}}